spring:
  h2:
    console:
      enabled: true
  http:
    log-request-details: true
  output:
    ansi:
      enabled: ALWAYS
  mvc:

logging:
  level:
    org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE


